name: i18n_extension_core
description: Dart-only package for Translation and Internationalization (i18n), with Dart extensions. Easy to use for both large and small projects.
version: 2.0.7
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/i18n_extension_core
topics:
  - internationalization
  - localization
  - translation
  - server
  - backend

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  sprintf: ^7.0.0

dev_dependencies:
  test: ^1.17.12
